In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv("../data/cardekho_imputated.csv",index_col=0)
df

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

* Handling Missing values 
* Handling Duplicates
* Check data type
* Understand the dataset

In [5]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [6]:
# Handling Duplicates
df[df.duplicated]

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
261,Honda City,Honda,City,8,70000,Individual,Petrol,Manual,16.80,1497,116.30,5,545000
462,Maruti Baleno,Maruti,Baleno,2,5000,Individual,Petrol,Automatic,21.40,1197,83.10,5,686000
1739,Maruti Swift Dzire,Maruti,Swift Dzire,4,50000,Individual,Diesel,Manual,28.40,1248,74.02,5,680000
1838,Maruti Wagon R,Maruti,Wagon R,13,100000,Individual,Petrol,Manual,18.90,1061,67.00,5,150000
1907,Hyundai i20,Hyundai,i20,3,50000,Individual,Petrol,Manual,18.60,1197,81.83,5,625000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19311,Maruti Swift,Maruti,Swift,8,80000,Individual,Diesel,Manual,22.90,1248,74.00,5,350000
19434,Maruti Wagon R,Maruti,Wagon R,6,50000,Individual,CNG,Manual,26.60,998,58.16,5,450000
19489,Tata Tiago,Tata,Tiago,4,30000,Individual,Petrol,Manual,23.84,1199,84.00,5,350000
19505,Hyundai Grand,Hyundai,Grand,6,30000,Individual,Petrol,Manual,18.90,1197,82.00,5,450000
19521,Land Rover Rover,Land Rover,Rover,5,128000,Dealer,Diesel,Automatic,12.63,2179,147.50,5,2675000

In [7]:
for i in df.columns:
    print(i)

car_name
brand
model
vehicle_age
km_driven
seller_type
fuel_type
transmission_type
mileage
engine
max_power
seats
selling_price

In [8]:
df.head(1)

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.7,796,46.3,5,120000

In [9]:
#droping unwanted columns
df.drop(columns=["brand","car_name"],inplace=True)

In [10]:
df

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...
19537,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
19540,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
19541,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
19542,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
19543,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [11]:
df.isnull().sum()

model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [12]:
df=df.drop_duplicates()
df

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...
19537,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
19540,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
19541,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
19542,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
19543,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [13]:
df.dtypes

model                    str
vehicle_age            int64
km_driven              int64
seller_type              str
fuel_type                str
transmission_type        str
mileage              float64
engine                 int64
max_power            float64
seats                  int64
selling_price          int64
dtype: object

In [14]:
categorical_columns=[feature for feature in df.columns if df[feature].dtype=="str"]
categorical_columns

['model', 'seller_type', 'fuel_type', 'transmission_type']

In [15]:
len(df.model.unique())

120

In [16]:
df.fuel_type.value_counts()

fuel_type
Petrol      7555
Diesel      7342
CNG          299
LPG           44
Electric       4
Name: count, dtype: int64

In [17]:
df.transmission_type.value_counts()

transmission_type
Manual       12094
Automatic     3150
Name: count, dtype: int64

In [18]:
df.seller_type.value_counts()

seller_type
Dealer              9459
Individual          5612
Trustmark Dealer     173
Name: count, dtype: int64

In [19]:
numerical_columns=[feature for feature in df.columns if df[feature].dtype!="str"]
numerical_columns

['vehicle_age',
 'km_driven',
 'mileage',
 'engine',
 'max_power',
 'seats',
 'selling_price']

In [20]:
discrite_features=[feature for feature in numerical_columns if len(df[feature].unique())<=25]
discrite_features

['vehicle_age', 'seats']

In [21]:
continuous_features=[feature for feature in numerical_columns if feature not in discrite_features ]
continuous_features

['km_driven', 'mileage', 'engine', 'max_power', 'selling_price']

In [22]:
print('Num of Numerical Features :', len(numerical_columns))
print('Num of catrgorical Features :', len(categorical_columns))
print('Num of Discrite Features :', len(discrite_features))
print('Num of continuous Features :', len(continuous_features))

Num of Numerical Features : 7
Num of catrgorical Features : 4
Num of Discrite Features : 2
Num of continuous Features : 5

In [23]:
# Spliting Independent and dependent features
X=df.drop(columns=['selling_price'])
y=df['selling_price']

In [24]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [25]:
y

0         120000
1         550000
2         215000
3         226000
4         570000
          ...
19537     250000
19540     925000
19541     425000
19542    1225000
19543    1200000
Name: selling_price, Length: 15244, dtype: int64

In [26]:
len(df.model.unique())

120

In [27]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
encoder=LabelEncoder()
X['model']=encoder.fit_transform(X['model'])

In [28]:
import pickle
with open("../models/LabelEncoder.pkl",'wb') as file:
    pickle.dump(encoder,file)
print("Model saved succesfully..")

Model saved succesfully..

In [29]:
len(df['seller_type'].unique()),len(df['fuel_type'].unique()),len(df['transmission_type'].unique())

(3, 5, 2)

In [30]:
num_features=X.select_dtypes(exclude="str").columns
onehot_columns = ['seller_type','fuel_type','transmission_type']
from sklearn.compose import ColumnTransformer
numerical_transformer=StandardScaler()
oh_transformer=OneHotEncoder(drop="first")

preprocesor=ColumnTransformer(
    [
        ("StandardScaler",numerical_transformer,num_features),
        ("OneHotEncoder",oh_transformer,onehot_columns),

    ],remainder='passthrough'
)

In [31]:
X=preprocesor.fit_transform(X)

In [32]:
import pickle
with open("../models/preprocessor.pkl",'wb') as file:
    pickle.dump(preprocesor,file)
print("Model saved succesfully..")

Model saved succesfully..

In [33]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,-1.519581,0.981015,1.243329,0.000640,-1.326227,-1.265491,-0.403299,1.0,0.0,0.0,0.0,0.0,1.0,1.0
1,-0.225821,-0.345188,-0.688493,-0.191245,-0.555669,-0.433600,-0.403299,1.0,0.0,0.0,0.0,0.0,1.0,1.0
2,1.535894,1.644117,0.084236,-0.646971,-0.555669,-0.480205,-0.403299,1.0,0.0,0.0,0.0,0.0,1.0,1.0
3,-1.519581,0.981015,-0.360084,0.293264,-0.938066,-0.780804,-0.403299,1.0,0.0,0.0,0.0,0.0,1.0,1.0
4,-0.666250,-0.013637,-0.495311,0.736997,0.022729,-0.047016,-0.403299,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15239,1.508367,0.981015,-0.867708,0.027024,-0.768966,-0.758667,-0.403299,0.0,0.0,0.0,0.0,0.0,1.0,1.0
15240,-0.556143,-1.339840,-0.727130,-0.527043,-0.217469,-0.221550,2.069705,0.0,0.0,0.0,0.0,0.0,1.0,1.0
15241,0.407295,-0.013637,0.219463,0.346032,0.022729,0.067864,-0.403299,0.0,0.0,1.0,0.0,0.0,0.0,1.0
15242,1.425787,-0.345188,72.334381,-0.886827,1.331332,0.917931,2.069705,0.0,0.0,1.0,0.0,0.0,0.0,1.0
15243,-1.024098,-1.339840,-0.823721,-0.407115,0.020808,0.395960,-0.403299,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [34]:
# separate dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((12195, 14), (3049, 14))

# Model Training

In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [36]:
##Create a Function to Evaluate Model
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [37]:
# Model Providing high R2 Score
model=XGBRegressor(n_estimators= 300,learning_rate=0.1,
                                     max_depth=5,colsample_bytree=0.5)
model.fit(X_train, y_train)
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

print('Model performance for Training set')
print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
print("- R2 Score: {:.4f}".format(model_train_r2))

print('----------------------------------')

print('Model performance for Test set')
print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
print("- R2 Score: {:.4f}".format(model_test_r2))

print('='*35)
print('\n')

Model performance for Training set
- Root Mean Squared Error: 115044.1835
- Mean Absolute Error: 74819.4766
- R2 Score: 0.9844
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 204161.5749
- Mean Absolute Error: 97531.4844
- R2 Score: 0.9314
===================================

In [38]:
# storing the model
import pickle
with open("../models/model.pkl",'wb') as file:
    pickle.dump(model,file)
print("Model saved succesfully..")

Model saved succesfully..

In [40]:
with open('../models/preprocessor.pkl', 'rb') as file:
    preprocessor = pickle.load(file)

with open('../models/model.pkl', 'rb') as file:
    model = pickle.load(file)
with open('../models/LabelEncoder.pkl', 'rb') as file:
    encoder = pickle.load(file)

In [41]:
items = [
    {
        "model": "i20", 
        "vehicle_age": 11, 
        "km_driven": 60000,
        "seller_type":"Individual",
        "fuel_type":"Petrol",
        "transmission_type":"Manual",
        "mileage":17.00,
        "engine":1197,
        "max_power":80.00,
        "seats":5
    }
]

In [42]:
C=pd.DataFrame(items)

In [45]:
def prediction(items):
    C=pd.DataFrame(items)
    with open('../models/preprocessor.pkl', 'rb') as file:
        preprocessor = pickle.load(file)

    with open('../models/model.pkl', 'rb') as file:
        model = pickle.load(file)
    with open('../models/LabelEncoder.pkl', 'rb') as file:
        encoder = pickle.load(file)
    C['model']=encoder.transform(C['model'])
    C=preprocesor.transform(C)
    pred = model.predict(C)
    print(pred)

In [46]:
prediction(items=items)

[270352.12]

In [47]:
C['model']=encoder.transform(C['model'])
C=preprocesor.transform(C)

In [48]:
C

array([[ 1.53589372,  1.6441169 ,  0.08423551, -0.64697105, -0.5556692 ,
        -0.48020502, -0.40329882,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  1.        ]])

In [49]:
y_train_pred = model.predict(C)

In [50]:
print(y_train_pred)

[270352.12]